# Generated by Django 3.1 on 2020-11-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_donordetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerdetails',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
