# Generated by Django 3.1 on 2020-11-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201115_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donordetails',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='seekerdetails',
            name='date_created',
        ),
    ]
