# Generated by Django 3.1 on 2020-11-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201115_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donordetails',
            old_name='name',
            new_name='dname',
        ),
        migrations.RenameField(
            model_name='seekerdetails',
            old_name='name',
            new_name='dname',
        ),
    ]
